---
title: "Cvir_Epi"
author: "HM Putnam"
date: "10/4/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Extract historical DNA methylation via calculation of CpGo/e for each gene in the C. virginica genome

## R Markdown


```{r, engine = 'bash'}



'for file in "file list"
do

perl -e '$count=0; $len=0; while(<>) {s/\r?\n//; s/\t/ /g; if (s/^>//) { if ($. != 1) {print "\n"} s/ |$/\t/; $count++; $_ .= "\t";} else {s/ //g; $len += length($_)} print $_;} print "\n"; warn "\nConverted $count FASTA records in $. lines to tabular format\nTotal sequence length: $len\n\n";' \ Pop_Fastas/{file} | cut -f1,3 > Output/{file}_fasta2tab

perl -e '$col = 1;' -e 'while (<>) { s/\r?\n//; @F = split /\t/, $_; $len = length($F[$col]); print "$_\t$len\n" } warn "\nAdded column with length of column $col for $. lines.\n\n";' \ Output/{file}_fasta2tab > Output/{file}_tab_1

awk '{print $2}' Output/{file}_tab_1 > Output/{file}_tab_2

echo "CG" | awk -F\[Cc][Gg] '{print NF-1}' Output/{file}_tab_2 > Output/{file}_CG 

echo "C" | awk -F\[Cc] '{print NF-1}' Output/{file}_tab_2 > Output/{file}_C 

echo "G" | awk -F\[Gg] '{print NF-1}' Output/{file}_tab_2 > Output/{file}_G 

paste Output/{file}_tab_1 \
Output/{file}_CG \
Output/{file}_C \
Output/{file}_G \
> Output/{file}_comb

awk '{print $1, "\t", (($4)/($5*$6))*(($3^2)/($3-1))}' Output/{file}_comb > Output/{file}_ID_CpG

awk '{print $2}' Output/{file}_ID_CpG | sed '/-nan/d' > Output/{file}_CpG
done'

```

```{GO Slim}
BP.Ids <- as.character(BP.INT$category)
myCollection <- GOCollection(BP.Ids)
fl <- "http://www.geneontology.org/ontology/subsets/goslim_generic.obo"
slim <- getOBOCollection(fl, evidenceCode="TAS")
BP.slim.INT <- goSlim(myCollection, slim, "BP")
BP.slim.INT <-BP.slim.INT[,c(1,3)]
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
